name: Build and Release iOS Tweak

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Set up Theos environment
      run: |
        # Cài đặt Homebrew nếu chưa có
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
        
        # Cài đặt dependencies cho Theos
        brew install ldid xz
        
        # Clone Theos
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
        # Thiết lập biến môi trường cho Theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/theos/bin" >> $GITHUB_ENV
        
        # Tải iOS SDKs
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $HOME
        mv $HOME/sdks-master/*.sdk $HOME/theos/sdks/
        rm master.zip
        
    - name: Install additional dependencies
      run: |
        # Thêm các dependencies khác ở đây nếu cần
        # brew install ...
        
    - name: Build iOS tweak
      run: |
        # Build tweak sử dụng make hoặc theos
        make package
        
    - name: Package build artifacts
      run: |
        mkdir -p ./artifacts
        # Di chuyển file .deb vào thư mục artifacts
        cp ./packages/*.deb ./artifacts/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-tweak-build
        path: ./artifacts/
        
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ios-tweak-build
        path: ./artifacts/
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./artifacts/*.deb
        draft: true
        prerelease: false
